# Generated by Django 5.1.7 on 2025-05-22 17:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('type', models.CharField(choices=[('spirit', 'Дух'), ('demon', 'Демон'), ('deity', 'Божество'), ('creature', 'Міфічна істота'), ('other', 'Інше')], max_length=100, verbose_name='Тип')),
                ('region', models.CharField(max_length=100, verbose_name='Регіон')),
                ('appearance', models.TextField(verbose_name='Зовнішність')),
                ('behavior', models.TextField(verbose_name='Поведінка')),
                ('role_in_mythology', models.TextField(verbose_name='Роль у міфології')),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Символи')),
                ('description', models.TextField(verbose_name='Взаємодія')),
                ('sources', models.TextField(verbose_name='Джерела')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('image', models.ImageField(blank=True, null=True, upload_to='creature_images/')),
            ],
            options={
                'verbose_name': 'Міфічна істота',
                'verbose_name_plural': 'Міфічні істоти',
                'db_table': 'creatures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture_url', models.TextField(blank=True, null=True)),
                ('activity', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creature.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Створення'), ('edit', 'Редагування'), ('approve', 'Затвердження'), ('reject', 'Відхилення'), ('delete', 'Видалення')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог дій',
                'verbose_name_plural': 'Логи дій',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CreatureDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('type', models.CharField(choices=[('spirit', 'Дух'), ('demon', 'Демон'), ('deity', 'Божество'), ('creature', 'Міфічна істота'), ('other', 'Інше')], max_length=100, verbose_name='Тип')),
                ('region', models.CharField(max_length=100, verbose_name='Регіон')),
                ('appearance', models.TextField(verbose_name='Зовнішність')),
                ('behavior', models.TextField(verbose_name='Поведінка')),
                ('role_in_mythology', models.TextField(verbose_name='Роль у міфології')),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Символи')),
                ('description', models.TextField(verbose_name='Взаємодія')),
                ('sources', models.TextField(verbose_name='Джерела')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Зображення')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подання')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Затверджено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Коментар адміна')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Відхилено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Чернетка істоти',
                'verbose_name_plural': 'Чернетки істот',
            },
        ),
    ]
