# Generated by Django 5.1.7 on 2025-04-14 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('type', models.CharField(choices=[('spirit', 'Дух'), ('demon', 'Демон'), ('deity', 'Божество'), ('creature', 'Міфічна істота'), ('other', 'Інше')], max_length=100, verbose_name='Тип')),
                ('region', models.CharField(max_length=100, verbose_name='Регіон')),
                ('appearance', models.TextField(verbose_name='Зовнішність')),
                ('behavior', models.TextField(verbose_name='Поведінка')),
                ('role_in_mythology', models.TextField(verbose_name='Роль у міфології')),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Символи')),
                ('interactions', models.TextField(verbose_name='Взаємодія')),
                ('sources', models.TextField(verbose_name='Джерела')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Міфічна істота',
                'verbose_name_plural': 'Міфічні істоти',
                'db_table': 'creatures',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
