# Generated by Django 5.1.7 on 2025-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creature',
            table='obriy',
        ),
    ]
