# Generated by Django 5.1.7 on 2025-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0002_alter_creature_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creature',
            table='obriy_db',
        ),
    ]
