# Generated by Django 5.1.7 on 2025-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0004_alter_creature_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Міфічна істота', 'verbose_name_plural': 'Міфічні істоти'},
        ),
    ]
