# Generated by Django 5.1.7 on 2025-04-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0005_alter_creature_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creature',
            new_name='Creatures',
        ),
    ]
