# Generated by Django 5.1.7 on 2025-04-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0006_rename_creature_creatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creatures',
            new_name='Creature',
        ),
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['name'], 'verbose_name': 'Міфічна істота', 'verbose_name_plural': 'Міфічні істоти'},
        ),
        migrations.AlterModelTable(
            name='creature',
            table='creatures',
        ),
    ]
