# Generated by Django 5.1.7 on 2025-04-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0007_rename_creatures_creature_alter_creature_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='interactions',
            new_name='description',
        ),
    ]
